# Site settings
title: MelonSpace
email: melonh0327@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Enjoy everyday
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://melonh.com" # the base hostname & protocol for your site
github_username:  melonHuang

# Build settings
markdown: redcarpet
ghlighter: pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "supersc    ript"]

